### ISSUE TITLE
Sentry Breadcrumbs

### ISSUE THREAD

**Issue by WangleLine** [JujuAdams/Snitch#21]
https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/
https://github.com/JujuAdams/Snitch/blob/main/scripts/__SnitchConfigPayloadSentry/__SnitchConfigPayloadSentry.gml

I could add this to snitch, if you'd like - Got it working in a local project already

**Comment by JujuAdams** [comment]
Wasn't planning on adding this because
1. Doesn't have a convenient analogue across the other services
2. Not sure what that API would look like (though admittedly I haven't given it much thought)
3. I experimented with it back along and didn't find it all that useful

Open to a discussion though

**Comment by WangleLine** [comment]
re 1+2:
I think it would be fine if it's a sentry-only set of functions. Like SnitchSentryBreadcrumb() or something.

Alternatively, maybe there's a way to pipe the regular log messages into breadcrumbs, if the user enables a macro for that? It obviously wouldn't cover the entire span of breadcrumb features that sentry optionally accepts, but that's not necessarily needed (I personally only make use of the message, data, and timestamp fields)

re 3:
Personally, I've found breadcrumbs really useful in Vividerie, because I don't have to guess what lead up to crashes, or if they were using the developer console to tamper with the game, or if the game crashed because of a recent settings change etc.

**Comment by JujuAdams** [comment]
1. ~~I don't have a counterargument other than "I don't wanna" so you win this one.~~ Wait, I do have a very weak counterargument! What about feature creep across the other services as well? Do we support whatever platform-specific things Bugsnag is doing? Feels like a rabbit hole that I'm not keen to put my toes into in case the rabbit lusts for programmer blood.
2. I'm unsure about whether *all* the breadcrumb features should be included. I can evisage a fluent interface but that seems really complex. The MVP according to your use case would be `...Breadcrumb(message, [data])` and we could add a `...BreadcrumbExt(struct)` for advanced use? (Timestamp would be autogenerated in both cases)
3. What other data are you tracking outside of breadcrumbs? What specific sorts of breadcrumbs are you tracking overall? Gimme detail pls

**Comment by WangleLine** [comment]
re 1:
Yeah that's totally fair. We don't have to support it all, and if you decide it's not worth it to add it to Snitch that would be very okay too - For my use case I've already made it work in my game, I was just thinking it'd be cool to share that functionality to whoever needs it too.

Slightly related: I recently found out Bugsnag also does breadcrumbs btw, but obviously in a somewhat different data format.

re 2:
oh yeah! That's exactly how I implemented breadcrumbs with snitch in vividerie yesterday. Just the message and optional data, with the timestamp auto-generated.

re 3:
I'm only tracking crashes and breadcrumbs.
I use breadcrumbs to track:
- Library initialisation
- Save data loading / saving
- Item pickups
- Item use
- Dungeon completion
- Enemy / Boss kills
- Settings changes
- Debug console interaction

**Comment by JujuAdams** [comment]
1. If you're getting mileage out of it and the cost is adding two relatively simple functions then I can get behind that.
2. `SnitchSentryBreadcrumb(message, [data])` is good then, though I would also want developers to be able to submit their own struct via `SnitchSentryBreadcrumbExt(struct)`.
3. Cool cool

Guess the next question is whether you wanna PR this or whether this is something you'd prefer me to do? If you do wanna make a PR then we should go a little deeper into how the functions should work.
