### ISSUE TITLE
hijacked SDM calls cannot log non-string types

### ISSUE THREAD

**Issue by Anapsys** [JujuAdams/Snitch#5]
When calling a debug message directly on a variable (EG `show_debug_message(array)`) with `SNITCH_HIJACK_SDM` on, the following error occurs:

`file_text_write_string argument 2 incorrect type (array) expecting a String (YYGS)
at gml_Script___SnitchLogString (line 76) - file_text_write_string(_file, _string);
", "message": "file_text_write_string argument 2 incorrect type (array) expecting a String (YYGS)", "script": "gml_Script___SnitchLogString" }`

My own quick workaround was to add `if !is_string(_string) _string = string(_string);` to the beginning of `__SnitchLogString()`.

**Comment by JujuAdams** [comment]
Thanks for reporting this! Resolved in [1.1.2](https://github.com/JujuAdams/Snitch/releases/tag/1.1.2)
