### ISSUE TITLE
Impossible to compile in yyc when setting SWITCH_HIJACK_SDM to false

### ISSUE THREAD

**Issue by morphonet** [JujuAdams/Snitch#6]
IDE 2.3.2.560
Runtime 2.3.2.426

To reproduce:
> change SWITCH_HIJACK_SDM to false,
> make a yyc build
> Error

In __SnitchSystem, line 69 (nice), 
>        return __SnitchLogString(_string);

Removing the return resolve the yyc compile error.

**Comment by JujuAdams** [comment]
Thanks for the bug report! I will look at it shortly. What version of Snitch are you using?

**Comment by morphonet** [comment]
on latest release 1.1.3
Script: __SnitchSystem at line 69 : No return value from expression (does expression have a return value??)

**Comment by JujuAdams** [comment]
Ah right ok, v2 doesn't have this issue. I'll patch this now.
